package uk.ac.ucl.shell.commands;

import uk.ac.ucl.shell.ShellGrammarParser;
import uk.ac.ucl.shell.commands.base.CommandInterface;
import uk.ac.ucl.shell.commands.base.CommandVisitor;
import uk.ac.ucl.shell.exceptions.*;

import java.io.InputStream;
import java.io.OutputStream;

/**
 * An output redirections passes the output of one commands execution as the input argument for another command. For
 * example, grep "Interesting String" &lt; text1.txt &gt; result.txt finds all lines of the file text1.txt that contain
 * the string Interesting String as a substring and saves them in the file result.txt.
 */
public class OutputRedirection implements CommandInterface {
    /**
     * Command to be executed
     */
    private final CommandInterface left;
    /**
     * Path to output file
     */
    private final String right;

    /**
     * Pre-processing for output redirection
     *
     * @param left
     *         Command interface that describes properties of the command on the left of output redirection
     * @param tree
     *         The tree that is generated by the parser to extract the arguments
     *
     * @throws CommandException
     *         Error in constructing of command
     */
    OutputRedirection(CommandInterface left, ShellGrammarParser.OutputRedirectionContext tree) throws CommandException {
        this.right = validateSetFilename(tree);
        this.left = left;
    }

    /**
     * Extracts filename of file to be written to
     *
     * @param tree
     *         Tree with an output redirection at root which will contain filename as an argument
     *
     * @return Filename
     *
     * @throws CommandException
     *         Error in processing of command
     */
    private String validateSetFilename(ShellGrammarParser.OutputRedirectionContext tree) throws CommandException {
        ShellGrammarParser.ArgumentContext argument = tree.argument();
        if (argument != null) {
            return argument.getText();
        } else {
            throw new CommandException("incorrect number/type of arguments");
        }
    }

    /**
     * Getter for command
     *
     * @return Command to be executed
     */
    public CommandInterface getLeft() {
        return left;
    }

    /**
     * Getter for file name
     *
     * @return Path to output file
     */
    public String getRight() {
        return right;
    }

    @Override public void eval(CommandVisitor commandVisitor, InputStream input, OutputStream output)
            throws UnsafeApplicationException, ApplicationException, CommandException, ExitException,
                   OutputWriteException {
        commandVisitor.visit(this, input);
    }
}